// this file is used only to sandbox requests, not needed for the program to run

POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "User1",
  "email": "User1Main@gmail.com",
  "password": "User1Haslo"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "Jerzyki",
  "password": "Justyniak"
}